In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler, Normalizer
from sklearn.pipeline import Pipeline

Using TensorFlow backend.

In [2]:
df = pd.read_csv('../train.csv')
print(df.shape)
df.head()

(10886, 12)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

In [3]:
df_train = df.copy()
df_train['month'] = pd.DatetimeIndex(df_train['datetime']).month
# df_train = df[df['datetime'] < '2011-02'].copy()
# df_train = df[(df['datetime'] > month_ini) & (df['datetime'] < month_end)].copy()
df_train['day'] = pd.DatetimeIndex(df_train['datetime']).day
df_train['dayofweek'] = pd.DatetimeIndex(df_train['datetime']).dayofweek
df_train['hour'] = pd.DatetimeIndex(df_train['datetime']).hour
df_train = df_train.drop('datetime', axis=1)
y = df_train['count'].copy()
df_train = df_train.drop(['casual','registered','count'], axis=1)
# df = df.drop(['casual','registered'], axis=1)
print(df_train.shape)
df_train.head()

(10886, 12)

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,month,day,dayofweek,hour
0,1,0,0,1,9.84,14.395,81,0.0,1,1,5,0
1,1,0,0,1,9.02,13.635,80,0.0,1,1,5,1
2,1,0,0,1,9.02,13.635,80,0.0,1,1,5,2
3,1,0,0,1,9.84,14.395,75,0.0,1,1,5,3
4,1,0,0,1,9.84,14.395,75,0.0,1,1,5,4

In [4]:
X = df_train.values
Y = y.values
def new_model():
    n_features = 12
    # create model
    model = Sequential()
    model.add(Dense(70, input_dim=n_features, init='normal', activation='relu'))
#     model.add(Dense(4, init='normal', activation='relu'))
    model.add(Dense(1, init='normal'))
    # Compile model
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model
estimators = []
estimators.append(('scale', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=new_model, nb_epoch=100, batch_size=5, verbose=2)))
pipeline = Pipeline(estimators)
pipeline.fit(X, Y)
# kfold = KFold(n_splits=7)
# %time results = cross_val_score(pipeline, X, Y, cv=kfold, verbose=2)
# print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

Epoch 1/100
4s - loss: 35356.8068
Epoch 2/100
4s - loss: 21735.4166
Epoch 3/100
4s - loss: 21031.0580
Epoch 4/100
4s - loss: 20458.3453
Epoch 5/100
4s - loss: 19881.0258
Epoch 6/100
4s - loss: 19332.6423
Epoch 7/100
4s - loss: 18837.3303
Epoch 8/100
4s - loss: 18406.1262
Epoch 9/100
4s - loss: 18057.1682
Epoch 10/100
4s - loss: 17765.9602
Epoch 11/100
4s - loss: 17565.5052
Epoch 12/100
4s - loss: 17383.0374
Epoch 13/100
4s - loss: 17237.9397
Epoch 14/100
4s - loss: 17108.0449
Epoch 15/100
4s - loss: 17017.5769
Epoch 16/100
4s - loss: 16943.3788
Epoch 17/100
4s - loss: 16861.7304
Epoch 18/100
4s - loss: 16793.2245
Epoch 19/100
4s - loss: 16718.0494
Epoch 20/100
4s - loss: 16667.2305
Epoch 21/100
4s - loss: 16616.7058
Epoch 22/100
4s - loss: 16566.4739
Epoch 23/100
4s - loss: 16521.7983
Epoch 24/100
4s - loss: 16470.2259
Epoch 25/100
4s - loss: 16424.7482
Epoch 26/100
4s - loss: 16381.6158
Epoch 27/100
4s - loss: 16344.9621
Epoch 28/100
4s - loss: 16302.0515
Epoch 29/100
4s - loss: 16259.8441
Epoch 30/100
4s - loss: 16219.0144
Epoch 31/100
4s - loss: 16176.9207
Epoch 32/100
4s - loss: 16148.0760
Epoch 33/100
4s - loss: 16111.2304
Epoch 34/100
4s - loss: 16053.0247
Epoch 35/100
4s - loss: 16021.6845
Epoch 36/100
4s - loss: 15975.6379
Epoch 37/100
4s - loss: 15927.0163
Epoch 38/100
4s - loss: 15858.3864
Epoch 39/100
4s - loss: 15775.0220
Epoch 40/100
4s - loss: 15714.2154
Epoch 41/100
4s - loss: 15627.0913
Epoch 42/100
4s - loss: 15508.2182
Epoch 43/100
4s - loss: 15414.3160
Epoch 44/100
4s - loss: 15343.0333
Epoch 45/100
4s - loss: 15248.5257
Epoch 46/100
4s - loss: 15175.6465
Epoch 47/100
4s - loss: 15092.6898
Epoch 48/100
4s - loss: 15010.5117
Epoch 49/100
4s - loss: 14937.3925
Epoch 50/100
4s - loss: 14866.3257
Epoch 51/100
4s - loss: 14778.1624
Epoch 52/100
4s - loss: 14710.0875
Epoch 53/100
4s - loss: 14634.9948
Epoch 54/100
4s - loss: 14558.5452
Epoch 55/100
4s - loss: 14496.1234
Epoch 56/100
4s - loss: 14410.4443
Epoch 57/100
4s - loss: 14356.4833
Epoch 58/100
4s - loss: 14287.6958
Epoch 59/100
4s - loss: 14217.5176
Epoch 60/100
4s - loss: 14158.2568
Epoch 61/100
4s - loss: 14084.3008
Epoch 62/100
4s - loss: 14033.5850
Epoch 63/100
4s - loss: 13992.9026
Epoch 64/100
4s - loss: 13939.7508
Epoch 65/100
4s - loss: 13890.3647
Epoch 66/100
4s - loss: 13831.6807
Epoch 67/100
4s - loss: 13778.6743
Epoch 68/100
4s - loss: 13732.6770
Epoch 69/100
4s - loss: 13696.3262
Epoch 70/100
4s - loss: 13629.6607
Epoch 71/100
4s - loss: 13610.2505
Epoch 72/100
4s - loss: 13554.9315
Epoch 73/100
4s - loss: 13511.2758
Epoch 74/100
4s - loss: 13473.6951
Epoch 75/100
4s - loss: 13447.8928
Epoch 76/100
4s - loss: 13409.7577
Epoch 77/100
4s - loss: 13372.1426
Epoch 78/100
4s - loss: 13343.3988
Epoch 79/100
4s - loss: 13302.2646
Epoch 80/100
4s - loss: 13259.1378
Epoch 81/100
4s - loss: 13231.7103
Epoch 82/100
4s - loss: 13217.1490
Epoch 83/100
4s - loss: 13178.2900
Epoch 84/100
4s - loss: 13146.9616
Epoch 85/100
4s - loss: 13115.1014
Epoch 86/100
4s - loss: 13094.8695
Epoch 87/100
4s - loss: 13061.4943
Epoch 88/100
4s - loss: 13029.3172
Epoch 89/100
4s - loss: 13017.5241
Epoch 90/100
4s - loss: 13000.6319
Epoch 91/100
4s - loss: 12961.5981
Epoch 92/100
4s - loss: 12950.0004
Epoch 93/100
4s - loss: 12928.3093
Epoch 94/100
5s - loss: 12918.0196
Epoch 95/100
4s - loss: 12876.0355
Epoch 96/100
4s - loss: 12857.7429
Epoch 97/100
4s - loss: 12838.1598
Epoch 98/100
4s - loss: 12822.6513
Epoch 99/100
4s - loss: 12789.3862
Epoch 100/100
4s - loss: 12771.4960

Pipeline(steps=[('scale', StandardScaler(copy=True, with_mean=True, with_std=True)), ('mlp', <keras.wrappers.scikit_learn.KerasRegressor object at 0x7fce7efc6f98>)])

## Prediction

In [5]:
df_test = pd.read_csv('../test.csv')
df_test.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed
0,2011-01-20 00:00:00,1,0,1,1,10.66,11.365,56,26.0027
1,2011-01-20 01:00:00,1,0,1,1,10.66,13.635,56,0.0000
2,2011-01-20 02:00:00,1,0,1,1,10.66,13.635,56,0.0000
3,2011-01-20 03:00:00,1,0,1,1,10.66,12.880,56,11.0014
4,2011-01-20 04:00:00,1,0,1,1,10.66,12.880,56,11.0014

In [6]:
dft = df_test.copy()
dft['month'] = pd.DatetimeIndex(dft['datetime']).month
# dft = df_test[df_test['datetime'] < '2011-02'].copy()
# dft = df_test[(df_test['datetime'] > month_ini) & (df_test['datetime'] < month_end)].copy()
dft['day'] = pd.DatetimeIndex(dft['datetime']).day
dft['dayofweek'] = pd.DatetimeIndex(dft['datetime']).dayofweek
dft['hour'] = pd.DatetimeIndex(dft['datetime']).hour
dft = dft.drop('datetime', axis=1)
print(dft.shape)
dft.head()

(6493, 12)

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,month,day,dayofweek,hour
0,1,0,1,1,10.66,11.365,56,26.0027,1,20,3,0
1,1,0,1,1,10.66,13.635,56,0.0000,1,20,3,1
2,1,0,1,1,10.66,13.635,56,0.0000,1,20,3,2
3,1,0,1,1,10.66,12.880,56,11.0014,1,20,3,3
4,1,0,1,1,10.66,12.880,56,11.0014,1,20,3,4

In [7]:
test_pred = pipeline.predict(dft)
test_pred[test_pred < 0] = 0

str_prediction = "datetime,count\n"
for i in range(0, len(test_pred)):
    datetime = df_test['datetime'][i]
    pred = int(round(test_pred[i]))
    str_prediction += "{},{}\n".format(datetime, pred)

# print(str_prediction)
f = open('pred_keras.csv','w')
f.write(str_prediction)
f.close()

# Month by month

In [29]:
def new_model():
    n_features = 11
    # create model
    model = Sequential()
    model.add(Dense(80, input_dim=n_features, init='normal', activation='relu'))
#     model.add(Dense(4, init='normal', activation='relu'))
    model.add(Dense(1, init='normal'))
    # Compile model
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [37]:
ranges = pd.date_range('2010-12-31 23:59:59', periods=25, freq='M').tolist()
ini = True
df_train = df.copy()
dft = df_test.copy()
df_train['datetime'] = pd.to_datetime(df_train['datetime'])
dft['datetime'] = pd.to_datetime(dft['datetime'])
for i in range(0, len(ranges)-1):
    print(ranges[i+1])
    df_month = df_train[(df_train['datetime'] > ranges[i]) & (df_train['datetime'] < ranges[i+1])].copy()
    df_month['day'] = pd.DatetimeIndex(df_month['datetime']).day
    df_month['dayofweek'] = pd.DatetimeIndex(df_month['datetime']).dayofweek
    df_month['hour'] = pd.DatetimeIndex(df_month['datetime']).hour
    Y = df_month['count'].values
    df_month = df_month.drop(['casual','registered','count','datetime'], axis=1)
    X = df_month.values
    estimators = []
    estimators.append(('scale', StandardScaler()))
    estimators.append(('mlp', KerasRegressor(build_fn=new_model, nb_epoch=100, batch_size=5, verbose=0)))
    pipeline = Pipeline(estimators)
    pipeline.fit(X, Y)
    dftm = dft[(dft['datetime'] > ranges[i]) & (dft['datetime'] < ranges[i+1])].copy()
    dftm['day'] = pd.DatetimeIndex(dftm['datetime']).day
    dftm['dayofweek'] = pd.DatetimeIndex(dftm['datetime']).dayofweek
    dftm['hour'] = pd.DatetimeIndex(dftm['datetime']).hour
    dates = dftm['datetime'].tolist()
    dftm = dftm.drop('datetime', axis=1)
    test_pred = pipeline.predict(dftm)
    test_pred[test_pred < 0] = 0
    str_prediction = ""
    if ini:
        str_prediction = "datetime,count\n"
        ini = False
    for j in range(0, len(test_pred)):
        datetime = dates[j]
        pred = int(round(test_pred[j]))
        str_prediction += "{},{}\n".format(datetime, pred)
    f = open('pred_keras2.csv','a')
    f.write(str_prediction)
    f.close()

2011-01-31 23:59:59
2011-02-28 23:59:59
2011-03-31 23:59:59
2011-04-30 23:59:59
2011-05-31 23:59:59
2011-06-30 23:59:59
2011-07-31 23:59:59
2011-08-31 23:59:59
2011-09-30 23:59:59
2011-10-31 23:59:59
2011-11-30 23:59:59
2011-12-31 23:59:59
2012-01-31 23:59:59
2012-02-29 23:59:59
2012-03-31 23:59:59
2012-04-30 23:59:59
2012-05-31 23:59:59
2012-06-30 23:59:59
2012-07-31 23:59:59
2012-08-31 23:59:59
2012-09-30 23:59:59
2012-10-31 23:59:59
2012-11-30 23:59:59
2012-12-31 23:59:59

In [36]:
ranges = pd.date_range('2010-12-31 23:59:59', periods=25, freq='M').tolist()
dftm = dft[(dft['datetime'] > ranges[1]) & (dft['datetime'] < ranges[2])].copy()
dates = dftm['datetime'].tolist()
dates[0]

Timestamp('2011-02-20 00:00:00')